{{- if .Values.Backend.File.Enabled }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "fullname" . }}-file
  annotations:
    volume.alpha.kubernetes.io/storage-class: {{ .Values.Backend.File.StorageClass | quote }}
spec:
  accessModes:
    - {{ .Values.Backend.File.AccessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.Backend.File.Size | quote }}
{{- end }}
