# Default values for syncthing.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

Name: syncthing 
Image: "pinterb/syncthing"
ImageTag: "0.14.7"
ImagePullPolicy: "Always"
Component: "syncthing"
Cpu: "200m"
Memory: "256Mi"

# For minikube, set this to NodePort, elsewhere use LoadBalancer
#ServiceType: LoadBalancer
ServiceType: NodePort
Ports:
  Container:
    Http: 8384
    Discovery: 21027
    Sync: 22000
  Service:
    Http: 8384
    Discovery: 21027
    Sync: 22000

## Persist data to a persitent volume
Persistence:
  Enabled: true
  StorageClass: generic
  AccessMode: ReadWriteOnce
  Size:
    Data: 8Gi
    Config: 100Mi
