# Default values for cert-mgr.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

Manager:
  Name: kube-cert-manager
  Image: "palmstonegames/kube-cert-manager"
  ImageTag: "0.3.1"
  ImagePullPolicy: "Always"
  Component: "kube-cert-manager"
  Cpu: "200m"
  Memory: "256Mi"

Proxy:
  Name: kubectl-proxy 
  Image: "palmstonegames/kubectl-proxy"
  ImageTag: "1.4.0"
  ImagePullPolicy: "Always"
  ContainerPort: 8001 
  Cpu: "200m"
  Memory: "256Mi"

Acme:
  MetaData: cloudutils-dot-io
  Domain: cloudutils.io
  Email: admin@cloudutils.io
  Provider:
    DNSimple:
      Enabled: true
      SecretKeyRef: dnsimple-acme
      SecretName: dnsimple-acme

Persistence:
  Enabled: true
  StorageClass: generic
  AccessMode: ReadWriteOnce
  Size: 8Gi
